name: build

on: [push]

jobs:
  build_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: retrieve certificate and decode it to a file
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
        run: |
          echo $CSC_LINK | base64 --decode > apple-cert.p12
      - name: add key to single keychain
        env:
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        run: |
          security create-keychain -p password buildagent.keychain
          security unlock-keychain -p password buildagent.keychain
          security list-keychains -d user -s buildagent.keychain
          security default-keychain -s buildagent.keychain
          security import ./apple-cert.p12 -k buildagent.keychain -P $CSC_KEY_PASSWORD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k password buildagent.keychain
      - name: electron mac os security identities
        run: security find-identity -v
      - name: install dependencies
        run: npm install
      - name: build
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          DEBUG: electron-packager,electron-osx-sign
        run: npm run make
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: makes
          path: out/make
    